### ISSUE TITLE
check how to publish npm package

### ISSUE THREAD

**Issue by kaczor6418** [web-hand/web-hand#18]

**Comment by wslabosz** [comment]
### Scope vs Unscoped
The first question is whether we want to publish the package under the name of the organization (scope) or not (scope associates the package with our organization, it's for naming conventions e.g. name would look like: @somescope/somepackagename)

Scope packages are not public by default, but can be marked as that
`npm publish --access public`

https://docs.npmjs.com/cli/v8/using-npm/scope

### Steps
So to publish the code to the npm registry (as an organization), we would have to:
1. Sign up for npm user account
2. Create a npm organization
3. In the project folder specify scope `npm init --scope=@my-org`
4. Generate a package.json specyfing the package and all the dependencies respecting the guidelines (https://docs.npmjs.com/package-name-guidelines)
5. Add descriptive README.md
6. run command `npm publish --access public` in the root project folder

### Continuous Integration
We'd have to generate an access token (by default it's generated with read/write access)
`npm token create` or on website.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/62252112/182944063-8b62d361-f3e6-4d23-bde9-00bd40a9cc75.png">

https://docs.npmjs.com/creating-and-viewing-access-tokens
https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow

Github integration
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
