### ISSUE TITLE
github workflow improvements

### ISSUE THREAD

**Issue by kaczor6418** [web-hand/web-hand#24]
We want to pull out common logic like running linter and tests to separated GH jobs and then reuse them in check-pr and publish actions. 

Nice to have:
We can also add action for adding code-coverage badges

**Comment by wslabosz** [comment]
So, we want to use an external code coverage service, with a feature of badge display on the repo site.
Three choices I've found:
All of them are free for open-source projects like ours.

- Coveralls: https://coveralls.io/features
   easy to use, used by many leading tech companies, official GitHub action with coverage deploy, 
   supports badges

- Codecov: https://docs.codecov.com/docs/
   also easy to use, and deploy, supports badges
   
- SonarCloud: https://sonarcloud.io/features
   most advanced, with many extra features like code analysis, also with local env support by extensions, 
   also supports badges
   
I would go with Coveralls, as it looks the easiest to use, considering SonarCloud, if we want to utilize the code analysis feature.

**Comment by kaczor6418** [comment]
> So, we want to use an external code coverage service, with a feature of badge display on the repo site. Three choices I've found: All of them are free for open-source projects like ours.
> 
> * Coveralls: https://coveralls.io/features
>   easy to use, used by many leading tech companies, official GitHub action with coverage deploy,
>   supports badges
> * Codecov: https://docs.codecov.com/docs/
>   also easy to use, and deploy, supports badges
> * SonarCloud: https://sonarcloud.io/features
>   most advanced, with many extra features like code analysis, also with local env support by extensions,
>   also supports badges
> 
> I would go with Coveralls, as it looks the easiest to use, considering SonarCloud, if we want to utilize the code analysis feature.

I also would go with Coveralls because this is an official way advised by GitHub and also [istanbul.js](https://istanbul.js.org/docs/tutorials/tap/#integrating-with-coveralls)
